// Types of actions for redux store
export enum WidgetActionTypes {
    WIDGET_ADDED = 'WIDGET_ADDED',
    WIDGET_REMOVED = 'WIDGET_REMOVED',
    WIDGET_UPDATED = 'WIDGET_UPDATED',
}

// Types of actions for redux store
export enum KitchenActionTypes {
    SAVE_KITCHEN_SUCCESS = 'SAVE_KITCHEN_SUCCESS',
    LOAD_KITCHEN_SUCCESS = 'LOAD_KITCHENS_SUCCESS',
    UPDATE_KITCHEN_SUCCESS = 'UPDATE_KITCHEN_SUCCESS',
    REMOVED_KITCHEN_SUCCESS = 'REMOVED_KITCHEN_SUCCESS',
}
// UNIT_ADDED = 'UNIT_ADDED',
// UNIT_REMOVED = 'UNIT_REMOVED',
// UNIT_UPDATED = 'UNIT_UPDATED',

// WALLUNIT_ADDED = 'WALLUNIT_ADDED',
// WALLUNIT_REMOVED = 'WALLUNIT_REMOVED',
// WALLUNIT_UPDATED = 'WALLUNIT_UPDATED',

// WALL_ADDED = 'WALL_ADDED',
// WALL_REMOVED = 'WALL_REMOVED',
// WALL_UPDATED = 'WALL_UPDATED',

// WORKTOP_ADDED = 'WORKTOP_ADDED',
// WORKTOP_REMOVED = 'WORKTOP_REMOVED',
// WORKTOP_UPDATED = 'WORKTOP_UPDATED',
