// Types of actions for redux store
export enum KitchenActionTypes {
    WIDGET_ADDED = 'WIDGET_ADDED',
    WIDGET_REMOVED = 'WIDGET_REMOVED',
    WIDGET_UPDATED = 'WIDGET_UPDATED',
    WIDGET_INFO_UPDATED= 'WIDGET_INFO_UPDATED',

    SAVE_KITCHEN_SUCCESS = 'SAVE_KITCHEN_SUCCESS',
    LOAD_KITCHEN_SUCCESS = 'LOAD_KITCHEN_SUCCESS',
    REMOVED_KITCHEN_SUCCESS = 'REMOVED_KITCHEN_SUCCESS',
}
